apiVersion: v1
kind: Service
metadata:
  name: crypto-server-service
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: crypto-server-service
  type: ClusterIP
