apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-server-deployment
  name: redis-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-server-deployment
    spec:
      containers:
      - image: redis
        name: redis
        ports:
          - containerPort: 6379
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pvc
status: {}
